services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd backend && gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: FLASK_ENV
        value: production
